---
engines:
  remark-lint:
    enabled: false
  cloc:
    enabled: true
languages:
  go:
    enabled: true
include_paths:
  - "**/*.go"
  - "go.mod"
  - "go.sum"
exclude_paths:
  - "playground/**"
  - "img/**"
  - "**/*.md"
  - "**/*.txt"