---
engines:
  remark-lint:
    enabled: false
  duplication:
    enabled: false
  metrics:
    enabled: false
  revive:
    enabled: true
    include_paths:
      - "main.go"
      - "main_test.go"
    config:
      languages:
        - "go"
languages:
  go:
    enabled: true
exclude_paths:
  - "img/**"
  - "playground/**"
  - "scripts/**"
  - "**/*.md"
  - "**/*.log"