# https://golangci-lint.run/docs/configuration/file
# https://golangci-lint.run/docs/linters
version: "2"
linters:
  # default: none
  # enable:
  #   - errcheck
  #   - gosimple
  #   - govet
  #   - ineffassign
  #   - staticcheck
  #   - unused
  #   - err113
  #   - unparam
  #   - gocritic
  #   - misspell
  #   - perfsprint
  default: all
  disable:
    - gosec
    - makezero
    - dupl
    - wsl
    - wsl_v5
    - goconst
    - gocognit
    - gocyclo
    - revive
    - maintidx
    - cyclop
    - depguard
    - forbidigo
    - funlen
    - godot
    - lll
    - mnd
    - nestif
    - nilerr
    - nlreturn
    - tagliatelle
    - varnamelen
    - wrapcheck
    - ireturn
    - nonamedreturns
    - exhaustruct
    - unconvert
    - copyloopvar
    - intrange
    - paralleltest
    - gochecknoglobals
    - prealloc