version: "2"

linters:
  default: none
  enable:
    # Default
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    # Autofix
    - gocritic
    - err113
    - canonicalheader
    - copyloopvar
    - dupword
    - errorlint
    - exptostd
    - fatcontext
    - ginkgolinter
    - goheader
    - iface
    - importas
    - intrange
    - mirror
    - misspell
    - nakedret
    - nolintlint
    - perfsprint
    - protogetter
    - sloglint
    - staticcheck
    - tagalign
    - testifylint
    - usestdlibvars
    - usetesting
    - whitespace
    # - godot
    # - nlreturn
    # - wsl_v5

  # default: all
  # disable:
  #   - revive
  #   - cyclop
  #   - gocyclo
  #   - maintidx
  #   - ireturn
  #   - nonamedreturns
  #   - depguard
  #   - dupl
  #   - exhaustruct
  #   - forbidigo
  #   - funlen
  #   - gochecknoglobals
  #   - gocognit
  #   - goconst
  #   - godoclint
  #   - gosec
  #   - lll
  #   - makezero
  #   - mnd
  #   - nestif
  #   - nilerr
  #   - noctx
  #   - noinlineerr
  #   - prealloc
  #   - tagliatelle
  #   - unconvert
  #   - varnamelen
  #   - wrapcheck
  #   - godot
  #   - nlreturn
  #   - wsl_v5