name: lazyjournal
version: '0.2.0'
summary: TUI for journalctl, logs in the file system, Docker and Podman containers
description: |
  Terminal user interface for journalctl (tool for reading logs from systemd), logs in the file system, syslog, kernel, Docker and Podman containers for quick viewing and filtering with fuzzy find and regex support (like fzf and grep).

base: core20
confinement: classic

architectures:
  - amd64

apps:
  lazyjournal:
    command: bin/lazyjournal

parts:
  lazyjournal:
    plugin: dump
    source: .
    stage-packages: []
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp ./bin/lazyjournal-0.2.0-linux-amd64 $SNAPCRAFT_PART_INSTALL/bin/lazyjournal