name: ⚠ Bug report
description: Report a bug or issue.
title: '[Bug]: '
labels: ['bug']
body:
  - type: dropdown
    id: system
    attributes:
      label: System
      default: 0
      options:
        - Linux
        - macOS
        - OpenBSD
        - FreeBSD
        - Windows
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      default: 0
      options:
        - amd64
        - arm64
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS version
      placeholder: Ubuntu 24.04, macOS 15.2, Windows 10 or other
    validations:
      required: true

  - type: checkboxes
    id: install-method
    attributes:
      label: Installation method
      options:
        - label: Binary
        - label: Package manager
        - label: Docker container
        - label: Source code

  - type: markdown
    attributes:
      value: |
        If you get errors using the executable, check that it works when running it from source (if you have Go installed), and add that to your list of installation methods.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe the problem and transmit the contents of the error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Before opening an issue if you have trouble loading lists or logs, please test access to logs on the command line. This will help us better understand the issue and resolve it faster.
        To find out what system commands are used during application execution, enable logging when starting the interface using the `-l/--logging` flag and check the `lazyjournal.log` file.