services:
  lazyjournal:
    image: lifailon/lazyjournal:alpine
    container_name: lazyjournal
    restart: unless-stopped
    privileged: true
    volumes:
      # Binaries and system libraries
      - /usr/bin/systemctl:/usr/bin/systemctl:ro
      - /usr/bin/journalctl:/usr/bin/journalctl:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - $HOME/.local/bin/docker-compose:/usr/bin/docker-compose:ro
      - /usr/local/bin/kubectl:/usr/bin/kubectl:ro
      - /lib64:/lib64:ro
      - /lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:ro
      # Systemd
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
      - /run/systemd/system:/run/systemd/system:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket:ro
      # Journald
      - /etc/machine-id:/etc/machine-id:ro
      # Filesystem
      - /var/log:/var/log:ro
      - /opt:/opt:ro
      - /home:/home:ro
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Read docker logs from filesystem
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Kubernetes configuration
      - $HOME/.kube/config:/root/.kube/config:ro
      # Custom lazyjournal configuration (optional)
      # - ./config.yml:/bin/config.yml:ro
    environment:
      - OPTIONS=
    tty: true
    stdin_open: true