name: CD

on:
  workflow_dispatch:
    inputs:
      Docker:
        description: 'Build and Push to Docker Hub'
        default: false
        type: boolean
      Snap:
        description: 'Build snap package'
        default: false
        type: boolean
      Snapcraft:
        description: 'Push to Snapcraft'
        default: false
        type: boolean
      Deb:
        description: 'Build and Push to Snapcraft'
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      if: ${{ github.event.inputs.Docker == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: ${{ github.event.inputs.Docker == 'true' }}
      run: |
        docker build -t lifailon/lazyjournal:latest .
        docker push lifailon/lazyjournal:latest

    - name: Install Go
      if: ${{ github.event.inputs.Docker != 'true' }}
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install snapcraft and build snap package
      if: ${{ github.event.inputs.Snap == 'true' || github.event.inputs.Snapcraft == 'true' }}
      run: |
        sudo apt update
        sudo apt install -y snapd
        sudo snap install snapcraft --classic
        snap version
        version=$(go run main.go -v)
        sed -i "s/0.7.7/$version/g" snapcraft.yaml
        snapcraft --destructive-mode
        sudo snap install *.snap --dangerous --classic
        echo "ARTIFACT_NAME=lazyjournal_$version_amd64" >> $GITHUB_ENV

    - name: Upload snap package
      if: ${{ github.event.inputs.Snap == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
      env:
        ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}

    - name: Login and push to Snapcraft
      if: ${{ github.event.inputs.Snapcraft == 'true' }}
      run: |
        # snapcraft export-login --snaps lazyjournal snap-login.txt
        export SNAPCRAFT_STORE_CREDENTIALS="${{ secrets.SNAPCRAFT_SECRET }}"
        snapcraft push *.snap

    - name: Build deb package
      if: ${{ github.event.inputs.Deb == 'true' }}
      run: |
        version=$(go run main.go -v)
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/lazyjournal-$version-linux-amd64
        mkdir -p lazyjournal/DEBIAN lazyjournal/usr/local/bin
        cp bin/lazyjournal-$version-linux-amd64 lazyjournal/usr/local/bin/lazyjournal
        echo "Package: lazyjournal" >> lazyjournal/DEBIAN/control
        echo "Version: $version" >> lazyjournal/DEBIAN/control
        echo "Architecture: amd64" >> lazyjournal/DEBIAN/control
        echo "Maintainer: https://github.com/Lifailon" >> lazyjournal/DEBIAN/control
        echo "Description: TUI for journalctl, logs in the file system and docker containers for quick viewing and filtering with fuzzy find and regex support." >> lazyjournal/DEBIAN/control
        dpkg-deb --build lazyjournal lazyjournal-$version-amd64.deb
        dpkg-deb --contents lazyjournal-$version-amd64.deb
        echo "ARTIFACT_NAME=lazyjournal-$version-amd64.deb" >> $GITHUB_ENV
        sudo dpkg -i lazyjournal-0.7.7-amd64.deb

    - name: Upload deb package
      if: ${{ github.event.inputs.Deb == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
      env:
        ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}