name: CD

on:
  workflow_dispatch:
    inputs:
      Docker:
        description: 'Build and Push to Docker Hub'
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      if: ${{ github.event.inputs.Docker == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Docker Buildx
      if: ${{ github.event.inputs.Docker == 'true' }}
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        install: true

    - name: Build and push Docker images for Linux on amd64 and arm64
      if: ${{ github.event.inputs.Docker == 'true' }}
      run: |
        # docker build -t lifailon/lazyjournal:latest .
        # docker push lifailon/lazyjournal:latest
        docker buildx build \
          --platform \
          linux/amd64,linux/arm64 \
          -t lifailon/lazyjournal \
          --push .
      continue-on-error: true