name: "[SAST] Semgrep"

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:
    inputs:
      Upload:
        description: 'Upload SARIF results file'
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    # A Docker image with semgrep installed
    container:
      image: semgrep/semgrep

    # Skip any PR created by dependabot
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v6

      - run: semgrep scan --config auto --sarif --output=semgrep.sarif

      - name: Upload SARIF results file
        if: ${{ github.event.inputs.Upload == 'true' }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif