name: "[SAST] Snyk"

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:
    inputs:
      Upload:
        description: 'Upload SARIF results file'
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  snyk:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
      - uses: actions/checkout@v6

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@8e119fbb6c251787721d34ba683ed48eba792766

      - name: Snyk Code analysis (SAST) and uploads result into GitHub
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Snyk OSS/SCA analysis and uploads result to Snyk
        run: snyk monitor --all-projects || true

      - name: Upload SARIF results file
        if: ${{ github.event.inputs.Upload == 'true' }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-code.sarif