name: "[SAST] Codacy"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v6

      - name: Fix encoding to UTF-8
        run: |
          find . -type f -name "*.go" | while read -r file; do
            if ! iconv -f UTF-8 -t UTF-8 "$file" >/dev/null 2>&1; then
              echo "File $file is not UTF-8"
              iconv -f CP1251 -t UTF-8 "$file" -o "$file.tmp" && mv "$file.tmp" "$file"
            fi
          done

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
